services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: nutrition_mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf

  mariadb:
    image: mariadb:11
    container_name: nutrition_mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root_pass
      MARIADB_DATABASE: nutrition_db
      MARIADB_USER: nutrition_user
      MARIADB_PASSWORD: nutrition_pass
    volumes:
      - mariadb_data:/var/lib/mysql

  mongodb:
    image: mongo:7
    container_name: nutrition_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  neo4j:
    image: neo4j:5
    container_name: nutrition_neo4j
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/neo4j_password
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

volumes:
  mariadb_data:
  mongodb_data:
  neo4j_data:
  neo4j_logs:
